on: [pull_request]
name: Codeball
jobs:
  codeball_job:
    runs-on: ubuntu-latest
    name: Codeball
    steps:
    
    - name: test label
      uses: sturdy-dev/codeball-action/labeler@beta
      with:
        name: "codeball:approved"
        color: "86efac" # green
        remove-label-names: "codeball:needs-review"
