on: [pull_request]
name: Codeball
jobs:
  codeball_job:
    runs-on: ubuntu-latest
    name: Codeball
    steps:
    - name: Trigger Codeball
      uses: sturdy-dev/codeball-action@remove-obsolete-approvals
      with:
        approvePullRequests: "true"
        labelPullRequestsWhenApproved: "true"
        labelPullRequestsWhenReviewNeeded: "false"
        failJobsWhenReviewNeeded: "false"
